from tkinter import *
from tkinter.ttk import Combobox
from tkinter import messagebox
root=Tk()
def quit():
    root.destroy()
root.title('Tours and Travels')
l1=Label(root,text='Username')
l1.grid(row=1)
l2=Label(root,text='Password')
l2.grid(row=2)
e1=Entry(root)
e1.grid(row=1,column=1)
e2=Entry(root)
e2.grid(row=2,column=1)

def place():
    root=Toplevel()
    l1=Label(root,text='CHOOSE THE PLACE TO VISIT',bg='light pink',font='BOLD')
    l1.grid(row=1,columnspan=4)
    def pay():
        messagebox.showinfo('Success','Your Booking Is Successful!!')
    def chd():
        root=Toplevel()
        l1=Label(root,text='Choose Any Package To Check Inclusions and Price')
        l1.grid(row=1,columnspan=5)
        def plat():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Chd\n2.Stay at Hotel Taj,5 Star\n3.Complementary Breakfast and Drinks\n4.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=10000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b1=Button(root,text='Platinum',command=plat)
        b1.grid(row=2)
        def gold():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Chd\n2.Stay at Hotel Shivalik,4 Star\n3.Complementary Breakfast\n4.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=8000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b2=Button(root,text='Gold',command=gold)
        b2.grid(row=2,column=1)
        def sil():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Chd\n2.Stay at Hotel Sunrise,3 Star\n3.Complementary Drinks\n4.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=6000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b3=Button(root,text='Silver',command=sil)
        b3.grid(row=2,column=2)
        def bro():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Chd\n2.Stay at Hotel Sunrise,3 Star\n3.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=5000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b4=Button(root,text='Bronze',command=bro)
        b4.grid(row=2,column=3)
        l=Label(root,text='You Can Check The Places To Visit And Available Hotel Options Below')
        l.grid(row=3,columnspan=5)
        l2=Label(root,text='Places To Visit')
        l2.grid(row=4)
        a=['Sukhna Lake','Rock Garden','Rose Garden','Shopping In Elante and Sector 17']
        b=Combobox(root,values=a)
        b.grid(row=4,column=1)
        l3=Label(root,text='List of Hotels')
        l3.grid(row=5)
        d=['Hotel Sunrise,3 Star','Hotel Shivalik,4 Star','Hotel Taj,5 Star']
        e=Combobox(root,values=d)
        e.grid(row=5,column=1)
        def check():
            root=Toplevel()
            l1=Label(root,text='Your Package Inclusions are')
            l1.grid(row=1)
            
    b1=Button(root,text='Chandigarh',fg='navy',command=chd)
    b1.grid(row=2)

    def Rajesthan():
        root=Toplevel()
        l1=Label(root,text='Choose Any Package To Check Inclusions and Price')
        l1.grid(row=1,columnspan=5)
        def plat():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Rajesthan Udaipur\n2.Stay at Hotel Lack Palace,5 Star\n3.Complementary Breakfast and Drinks\n4.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=10000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b1=Button(root,text='Platinum',command=plat)
        b1.grid(row=2)
        def gold():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Rajesthan Jaipur\n2.Stay at JW Marriot,4 Star\n3.Complementary Breakfast\n4.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=8000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b2=Button(root,text='Gold',command=gold)
        b2.grid(row=2,column=1)
        def sil():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Rajesthan Jodhpur\n2.Stay at Hotel Hyatt,3 Star\n3.Complementary Drinks\n4.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=6000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b3=Button(root,text='Silver',command=sil)
        b3.grid(row=2,column=2)
        def bro():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Rajesthan Ajmar\n2.Stay at Hotet Relaxin,3 Star\n3.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=5000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b4=Button(root,text='Bronze',command=bro)
        b4.grid(row=2,column=3)
        l=Label(root,text='You Can Check The Places To Visit And Available Hotel Options Below')
        l.grid(row=3,columnspan=5)
        l2=Label(root,text='Places To Visit')
        l2.grid(row=4)
        a=['Desert Sfari','Faithe Sagar','Rani road','Shopping For Souveniers']
        b=Combobox(root,values=a)
        b.grid(row=4,column=1)
        l3=Label(root,text='List of Hotels')
        l3.grid(row=5)
        d=['Relaxin,3 Star','JW Marriot,4 Star','Lack Palace,5 Star']
        e=Combobox(root,values=d)
        e.grid(row=5,column=1)
        def check():
            root=Toplevel()
            l1=Label(root,text='Your Package Inclusions are')
            l1.grid(row=1)

    
    b2=Button(root,text='Rajesthan',fg='magenta',command=Rajesthan)
    b2.grid(row=2,column=1)

    def asr():
        root=Toplevel()
        l1=Label(root,text='Choose Any Package To Check Inclusions and Price')
        l1.grid(row=1,columnspan=5)
        def plat():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Amritsar\n2.Stay at Hotel Taj,5 Star\n3.Complementary Breakfast and Drinks\n4.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=10000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b1=Button(root,text='Platinum',command=plat)
        b1.grid(row=2)
        def gold():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Amritsar\n2.Stay at Hotel Shivalik,4 Star\n3.Complementary Breakfast\n4.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=8000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b2=Button(root,text='Gold',command=gold)
        b2.grid(row=2,column=1)
        def sil():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Amritsar\n2.Stay at Hotel Sunrise,3 Star\n3.Complementary Drinks\n4.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=6000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b3=Button(root,text='Silver',command=sil)
        b3.grid(row=2,column=2)
        def bro():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Amritsar\n2.Stay at Hotel Sunrise,3 Star\n3.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=5000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b4=Button(root,text='Bronze',command=bro)
        b4.grid(row=2,column=3)
        l=Label(root,text='You Can Check The Places To Visit And Available Hotel Options Below')
        l.grid(row=3,columnspan=5)
        l2=Label(root,text='Places To Visit')
        l2.grid(row=4)
        a=['Golden Temple','Jallianwala Bagh','Ataari Border','Shopping At Trillium Mall And Mall Road']
        b=Combobox(root,values=a)
        b.grid(row=4,column=1)
        l3=Label(root,text='List of Hotels')
        l3.grid(row=5)
        d=['Hotel Sunrise,3 Star','Hotel Shivalik,4 Star','Hotel Taj,5 Star']
        e=Combobox(root,values=d)
        e.grid(row=5,column=1)
        def check():
            root=Toplevel()
            l1=Label(root,text='Your Package Inclusions are')
            l1.grid(row=1)

    
    b3=Button(root,text='Amritsar',fg='dark green',command=asr)
    b3.grid(row=2,column=2)

    def delhi():
        root=Toplevel()
        l1=Label(root,text='Choose Any Package To Check Inclusions and Price')
        l1.grid(row=1,columnspan=5)
        def plat():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Delhi\n2.Stay at Hotel Taj,5 Star\n3.Complementary Breakfast and Drinks\n4.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=10000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b1=Button(root,text='Platinum',command=plat)
        b1.grid(row=2)
        def gold():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Delhi\n2.Stay at Hotel Shivalik,4 Star\n3.Complementary Breakfast\n4.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=8000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b2=Button(root,text='Gold',command=gold)
        b2.grid(row=2,column=1)
        def sil():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Delhi\n2.Stay at Hotel Sunrise,3 Star\n3.Complementary Drinks\n4.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=6000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b3=Button(root,text='Silver',command=sil)
        b3.grid(row=2,column=2)
        def bro():
            root=Toplevel()
            l1=Label(root,text='Package Inclusions:\n\n1.Arrival at ISBT Delhi\n2.Stay at Hotel Sunrise,3 Star\n3.Visit To All Tourist Places')
            l1.grid(row=1)
            l2=Label(root,text='Package Price=5000(taxes extra)')
            l2.grid(row=2)
            b1=Button(root,text='Book And Pay Now',command=pay)
            b1.grid(row=3)
            def back():
                root.destroy()
            b2=Button(root,text='Back',command=back)
            b2.grid(row=3,column=1)
            b3=Button(root,text='Quit',command=quit)
            b3.grid(row=3,column=2)
        b4=Button(root,text='Bronze',command=bro)
        b4.grid(row=2,column=3)
        l=Label(root,text='You Can Check The Places To Visit And Available Hotel Options Below')
        l.grid(row=3,columnspan=5)
        l2=Label(root,text='Places To Visit')
        l2.grid(row=4)
        a=['Red Fort','Qutub Minar','Old Delhi','Shopping at Canaught Palace ']
        b=Combobox(root,values=a)
        b.grid(row=4,column=1)
        l3=Label(root,text='List of Hotels')
        l3.grid(row=5)
        d=['Hotel Sunrise,3 Star','Hotel Shivalik,4 Star','Hotel Taj,5 Star']
        e=Combobox(root,values=d)
        e.grid(row=5,column=1)
        def check():
            root=Toplevel()
            l1=Label(root,text='Your Package Inclusions are')
            l1.grid(row=1)

    
    b4=Button(root,text='Delhi',fg='red',command=delhi)
    b4.grid(row=2,column=3)

def login():
    if e1.get()=='Rahul' and e2.get()=='142119':
        place()
    else:
        messagebox.showerror('Error','Wrong Username Or Password')


b1=Button(root,text='Login',command=login)
b1.grid(row=3)
b2=Button(root,text='Quit',command=quit)
b2.grid(row=3,column=1)
